item1=input("Enter Name of first Item")
q1=int(input("Enter quantity of first Item"))
p1=int(input("Enter first quantity price"))
item2=input("Enter Name of second Item")
q2=int(input("Enter quantity of second Item"))
p2=int(input("Enter second quantity price"))
item3=input("Enter Name of third Item")
q3=int(input("Enter quantity of third Item"))
p3=int(input("Enter third quantity price"))
print("**********************Bill*********************")
print("Item     Quantity  Price  Amount ")
print(item1,"   ",q1,"       ",p1,"    ",p1*q1)
print(item2," ",q2,"       ",p2,"    ",p2*q2)
print(item3,"  ",q3,"       ",p3,"    ",p3*q3)
print("Total Amount:",p1*q1+p2*q2+p3*q3)
print("************************************************")